[build]
  command = "npm install && npm run build --no-uglify && node node_modules/pug-cli/index.js views/ --out ./dist && cp -R public/. dist/"
  functions = "functions"
[[redirects]]
  from = "/*"
  to = "/home.html"
  status = 200
[build.environment]
  NODE_VERSION = "16.20.0"